CREATE TABLE XetDuyetDeTai (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  MaDT VARCHAR(50) NOT NULL,
  TaiKhoanHoiDong VARCHAR(50) NOT NULL,
  TrangThai NVARCHAR(30) NOT NULL
    CONSTRAINT DF_XetDuyetDeTai_TrangThai DEFAULT N'Chờ phê duyệt',
  GhiChu NVARCHAR(MAX) NULL,
  NgayPhanHoi DATETIME NULL,
  NgayTao DATETIME NOT NULL
    CONSTRAINT DF_XetDuyetDeTai_NgayTao DEFAULT GETDATE(),

  CONSTRAINT UQ_XetDuyetDeTai_MaDT_TaiKhoanHoiDong
    UNIQUE (MaDT, TaiKhoanHoiDong),

  CONSTRAINT FK_XetDuyetDeTai_DeTai
    FOREIGN KEY (MaDT) REFERENCES DeTai(MaDT),

  CONSTRAINT FK_XetDuyetDeTai_NguoiDung
    FOREIGN KEY (TaiKhoanHoiDong) REFERENCES NguoiDung(TaiKhoan)
);
